Merge normal and noroot script into one file

diff --git a/install-oldsu b/install-oldsu
--- a/install-oldsu
+++ b/install-oldsu
@@ -1,10 +1,18 @@
 #!/bin/bash
 
-echo "ROOT IS REQUIRED TO ADD OSU TO /usr/bin and /usr/share"
-sudo echo "Thanks!"
+if [[ $1 && $1 == "--no-root" ]]; then
+  no_root=true
+else
+  no_root=false
+fi
 
-if [[ $? != 0 ]] ; then
-  exit
+if [[ $no_root == "false" ]]; then
+  echo "ROOT IS REQUIRED TO ADD OSU TO /usr/bin and /usr/share"
+  sudo echo "Thanks!"
+
+  if [[ $? != 0 ]] ; then
+    exit
+  fi
 fi
 
 TMP_DIR="/tmp/oldsu-wine"
@@ -61,6 +69,12 @@ echo "If wine asks you to install wine mono or wine gecko, say no or cancel. Thi
 $WINETRICKS --force dotnet45 # force flag for recent wine 5.x versions; no -q so the user knows whats happening
 $WINETRICKS -q cjkfonts gdiplus ffdshow quartz # fixes fonts, graphics and videos
 
+print_sect "ALSA"
+if [[ "$ALSATWEAK" == "true" ]]; then
+  $WINETRICKS sound=alsa
+else
+  echo "Skipping ALSA tweak."
+fi
 
 # change directory to newly created prefix
 cd "$WINEPREFIX"
@@ -70,13 +84,9 @@ print_sect "dsound tweak"
 cat > dsound.reg << "EOF"
 Windows Registry Editor Version 5.00
 
-
 [HKEY_CURRENT_USER\Software\Wine\DirectSound]
-
 "HelBuflen"="512"
-
 "SndQueueMax"="3"
-
 EOF
 
 "$WINE" regedit dsound.reg
@@ -108,6 +118,7 @@ fi
 cat > oldsu << "EOF"
 #!/bin/sh
 export vblank_mode=0
+export __GL_SYNC_TO_VBLANK=0
 export WINEARCH=win32
 EOF
 
@@ -126,9 +137,17 @@ fi
 
 echo "\"$WINE\" \"$WINEPREFIX/drive_c/oldsu/osu!flandremod.exe\" \"\$@\"" >> oldsu
 
-print_sect "REQUESTING ROOT ACCESS TO ADD OLDSU TO /usr/bin"
-sudo mv oldsu /usr/bin/oldsu
-sudo chmod +x /usr/bin/oldsu
+if [[ $no_root == "true" ]]; then
+  # creating bin folder in .local to avoid use of root in case it doesn't exist
+  # remember to add the folder to your $PATH by issuing "export PATH=$HOME/.local/bin:$PATH" in a terminal
+  mkdir -p "$HOME/.local/bin/"
+  mv oldsu $HOME/.local/bin/oldsu
+  chmod +x $HOME/.local/bin/oldsu
+else
+  print_sect "REQUESTING ROOT ACCESS TO ADD OLDSU TO /usr/bin"
+  sudo mv oldsu /usr/bin/oldsu
+  sudo chmod +x /usr/bin/oldsu
+fi
 
 # Kill script
 cat > oldsukill << "EOF"
@@ -139,8 +158,13 @@ EOF
 echo "export WINEPREFIX=\"$WINEPREFIX\"" >> oldsukill
 echo "\"$WINESERVER\" -k" >> oldsukill
 
-sudo mv oldsukill /usr/bin/oldsukill
-sudo chmod +x /usr/bin/oldsukill
+if [[ $no_root == "true" ]]; then
+  mv oldsukill $HOME/.local/bin/oldsukill
+  chmod +x $HOME/.local/bin/oldsukill
+else
+  sudo mv oldsukill /usr/bin/oldsukill
+  sudo chmod +x /usr/bin/oldsukill
+fi
 
 # Desktop file
 OLDSU_LOGO_URL="https://cdn.discordapp.com/attachments/762549406091575309/783088957776461824/oldsu.png"
@@ -148,23 +172,14 @@ wget "$OLDSU_LOGO_URL" -O "$HOME/.local/share/icons/oldsulogo.png"
 
 cat > "oldsu!.desktop" << "EOF"
 [Desktop Entry]
-
 Encoding=UTF-8
-
 Name=oldsu!
-
 Comment=Travel back in time! Launch the 2008 o(ld)su! client.
-
 Type=Application
-
 Exec=oldsu %F
-
 Icon=oldsulogo
-
 StartupWMClass=osu!flandremod.exe
-
 Categories=Games
-
 EOF
 
 mv "oldsu!.desktop" "$HOME/.local/share/applications"
