More sane defaults, can now specify WINEPREFIX, WINE, WINESERVER, WINECFG, and WINETRICKS in environment, cleanup

diff --git a/install-osu b/install-osu
--- a/install-osu
+++ b/install-osu
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -e # play it safe
 
 echo "ROOT IS REQUIRED TO ADD OSU TO /usr/bin and /usr/share"
 sudo echo "Thanks!"
@@ -7,6 +8,10 @@ sudo echo "Thanks!"
 if [[ $? != 0 ]] ; then
   exit
 fi
+
+TMP_DIR="/tmp/osu-wine"
+mkdir -p "$TMP_DIR"
+cd "$TMP_DIR" # Create tmp files here.
 
 # Styling
 BORDER="========================================================================"
@@ -18,21 +23,32 @@ print_sect () {
 }
 
 print_sect "ATTENTION: THIS SCRIPT ASSUMES WINE AND WINETRICKS ARE ALREADY INSTALLED"
-echo "See https://osu.ppy.sh/community/forums/topics/367783"
 
 
 
 # Wine environ
-export WINEPREFIX="$HOME/osu-wine"
+if [[ ! -n "$WINEPREFIX" ]] ; then
+  export WINEPREFIX="$HOME/osu-wine"
+fi
+if [[ ! -n "$WINE" ]] ; then
+  export WINE="wine"
+fi
+if [[ ! -n "$WINESERVER" ]] ; then
+  export WINESERVER="wineserver"
+fi
+if [[ ! -n "$WINETRICKS" ]] ; then
+  export WINETRICKS="winetricks"
+fi
+if [[ ! -n "$WINECFG" ]] ; then
+  export WINECFG="winecfg"
+fi
 export WINEARCH=win32
 
 
 
 # COMMANDS
-WINETRICKS="winetricks"
 WINETRICKS_CREATE_PREFIX="$WINETRICKS -q dotnet462 cjkfonts gdiplus"
-WINETRICKS_ALSA="$WINETRICKS sound=alsa"
-WINECFG="winecfg"
+WINETRICKS_ALSA="$WINETRICKS sound=alsa"https://github.com/mrniceguy127/osu-wine-install-script
 
 
 # Create wineprefix
@@ -43,6 +59,7 @@ $WINETRICKS_CREATE_PREFIX
 # Manual winecfg step
 print_sect "MANUAL STEP"
 echo "> \"navigate to graphics and ensure that "allow the window manager to decorate the windows" and "allow the window manager to control the windows" are enabled. this can allow native fullscreen to work which can help performance on bloated desktop environments like gnome\""
+echo "See https://osu.ppy.sh/community/forums/topics/367783"
 
 $WINECFG
 
@@ -70,32 +87,28 @@ Windows Registry Editor Version 5.00
 
 EOF
 
-wine regedit dsound.reg
+"$WINE" regedit dsound.reg
 
 print_sect "osu! installer step. PLEASE CLOSE OSU WHEN LAUNCHED."
 # osu! Installer
-DL_PATH="$HOME/Downloads"
 
-if [[ -e "$DL_PATH/osu!install.exe" ]]; then
+if [[ -e "osu!install.exe" ]]; then
   echo "osu! installer already downloaded!"
 else
-  wget 'https://m1.ppy.sh/r/osu!install.exe' -P "$DL_PATH"
+  wget 'https://m1.ppy.sh/r/osu!install.exe'
 fi
 
-wine "$DL_PATH/osu!install.exe" &> /dev/null
-
-rm "$HOME/Downloads/osu!install.exe"
+$WINE "osu!install.exe"
 
 
 print_sect "POST INSTALL STEPS"
 # Post install
-# When editing this variable, please remember that other parts of this script hardcode the default value (see further down).
 OSU_SC_PATH="$HOME/osu"
 
-ln -sv "$HOME/osu-wine/drive_c/users/$USER/Local Settings/Application Data/osu!" "$OSU_SC_PATH"
-
-rm dsound.reg
-
+if [[ ! -e $OSU_SC_PATH ]] ; then
+  ln -sv "$WINEPREFIX/drive_c/users/$USER/Local Settings/Application Data/osu!" "$OSU_SC_PATH"
+  echo "Created osu! folder shortcut in current user's home."
+fi
 
 # Launch script
 
@@ -109,14 +122,13 @@ export vblank_mode=0
 
 export WINEARCH=win32
 
-export WINEPREFIX=$HOME/osu-wine
-
-wine "$HOME/osu/osu!.exe" "$@"
-
 EOF
 
+echo "export WINEPREFIX=\"$WINEPREFIX\""  >> osu
+echo "\"$WINE\" \"$WINEPREFIX/drive_c/users/\$USER/Local Settings/Application Data/osu!/osu!.exe\" \"\$@\"" >> osu
 
-sudo mv osu /usr/bin/
+
+sudo mv osu /usr/bin/osu
 sudo chmod +x /usr/bin/osu
 
 
@@ -130,14 +142,13 @@ export vblank_mode=0
 
 export WINEARCH=win32
 
-export WINEPREFIX=$HOME/osu-wine
-
-wineserver -k
-
 EOF
 
+echo "export WINEPREFIX=\"$WINEPREFIX\"" >> osukill
+echo "\"$WINESERVER\" -k" >> osukill
 
-sudo mv osukill /usr/bin/
+
+sudo mv osukill /usr/bin/osukill
 sudo chmod +x /usr/bin/osukill
 
 
@@ -150,7 +161,7 @@ OSU_LOGO_URL="https://i.ppy.sh/916068c8e2d5f90be7766da5ce0ee7a7ea6c99b3/68747470
 
 sudo wget "$OSU_LOGO_URL" -O "/usr/share/icons/osulogo.png"
 
-cat > "$HOME/osu-wine/osu!.desktop" << "EOF"
+cat > "osu!.desktop" << "EOF"
 [Desktop Entry]
 
 Encoding=UTF-8
@@ -171,14 +182,17 @@ Categories=
 
 EOF
 
-sudo mv "$HOME/osu-wine/osu!.desktop" "/usr/share/applications"
+sudo mv "osu!.desktop" "/usr/share/applications"
 sudo chmod +x "/usr/share/applications/osu!.desktop"
 
 
 
 
 
+# Cleanup
+cd /tmp
+rm -r "$TMP_DIR"
 
 
 # Finished!
-print_sect "Finished!"
+print_sect "Finished! Please report any issues with this script at https://github.com/mrniceguy127/osu-wine-install-script"
